### ISSUE TITLE
annoying user prompts to delete file  "$HOME"/.bashish/tmp/*/sync when rm is aliased

### ISSUE THREAD

**Issue by kforner** [arnognulf/bashish#1]
Hello,

When an alias is defined for the rm command, e.g. alias rm='rm -i ', each time a new bash is launched you get a prompt for deleting the file "$HOME"/.bashish/tmp/*/sync".

This alias is "classic", and sometimes defined at the system level (/etc/bash.bashrc) so it is not so easy to remove it on a user basis.

I humbly suggest to use \rm instead of rm in the bashish code in places that should not be interactive, for instance in data/main/bashish/sys/update line 28 and 38.

Thanks for that useful software !

**Comment by arnognulf** [comment]
Hi, glad you liked it!

I've updated Bashish to escape rm at all places where rm was used unesacped.

Hope this helps.

Best regards
/Thomas

**Comment by kforner** [comment]
Cool, thanks..!
Le 22 déc. 2013 23:48, "Thomas Eriksson" notifications@github.com a écrit
:
